//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolGradingSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int NoteID { get; set; }
        public Nullable<byte> LessonID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<byte> Exam1 { get; set; }
        public Nullable<byte> Exam2 { get; set; }
        public Nullable<byte> Exam3 { get; set; }
        public Nullable<byte> Project { get; set; }
        public Nullable<decimal> Average { get; set; }
        public Nullable<bool> Statu { get; set; }
    
        public virtual Lessons Lessons { get; set; }
        public virtual Students Students { get; set; }
    }
}
